### ISSUE TITLE
Image Uploaded

### ISSUE THREAD

**Issue by halaziliuyidi** [dou-d/stranzee#1]
![image](https://user-images.githubusercontent.com/27996138/206667786-d7817fa9-a9d3-4769-81b0-bc9305bb2738.png)
Hello, I had the problem in the picture when I used the app to register. Could you help me？

**Comment by dipudl** [comment]
Please make sure the android/client app is actually sending the image. You can check the 'uploads' folder in your node.js codebase.

**Comment by halaziliuyidi** [comment]
Yes, the picture did upload, but I wonder why it didn't load
![image](https://user-images.githubusercontent.com/27996138/206700776-576e1617-910d-4530-a009-7cfad49dc82a.png)

**Comment by halaziliuyidi** [comment]
I can see why this error is occurring. Do I read the path using the absolute path

**Comment by halaziliuyidi** [comment]
Thank you for your support
